name: restore-pnpm-store-cache
description: |
  restore pnpm store cache
  requires pnpm setup

outputs:
  cache-hit:
    description: ''
    value: ${{ steps.restore-pnpm-store-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Get pnpm store directory
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Restore pnpm-store cache
      id: restore-pnpm-store-cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
