name: restore-pnpm-store-cache
description: |
  restore pnpm store cache
  requires pnpm setup

runs:
  using: 'composite'
  steps:
    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Restore pnpm-store cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
