name: build-uniproc

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        with:
          REQUIRE_BUN: 'false'
      - uses: ./.github/actions/restore-pnpm-store-cache
      - name: Restore uniproc-dist cache
        uses: actions/cache/restore@v4
        with:
          path: ./uniproc/dist
          key: uniproc-dist-${{ github.sha }}
      - name: Install at sveltecf
        run: pnpm install
        working-directory: ./sveltecf
      - run: pnpm sveltecf build
      - name: Save sveltecf-kit cache
        uses: actions/cache/save@v4
        with:
          path: ./sveltecf/.svelte-kit
          key: sveltecf-kit-${{ github.sha }}
