name: _build-uniproc

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - uses: ./.github/actions/restore-pnpm-store-cache
      - name: Install at uniproc
        run: pnpm install
        working-directory: ./uniproc
      - run: pnpm uniproc build
      - name: Save uniproc-dist cache
        uses: actions/cache/save@v4
        with:
          path: ./uniproc/dist
          key: uniproc-dist-${{ github.sha }}
