name: install-pnpm-deps

on:
  workflow_call:
    inputs:
      use-pnpm-store-cache:
        type: boolean
        required: false
        default: true

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      PNPM_STORE_PATH: ''
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
        with:
          REQUIRE_BUN: 'false'
      - uses: ./.github/actions/restore-pnpm-store-cache
        id: restore-pnpm-store-cache
        if: inputs.use-pnpm-store-cache == true
      - run: pnpm install
        if: steps.restore-pnpm-store-cache.outputs.cache-hit != 'true'
      - name: Get pnpm store directory
        run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Save pnpm-store cache
        uses: actions/cache/save@v3
        if: steps.restore-pnpm-store-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
