name: Build🔨, Verify🧪 on push

on: push

jobs:
  install-pnpm-deps:
    uses: ./.github/workflows/install-pnpm-deps.yaml

  build-uniproc:
    needs: install-pnpm-deps
    uses: ./.github/workflows/build-uniproc.yaml

  build-sveltecf:
    needs:
      - install-pnpm-deps
      - build-uniproc
    uses: ./.github/workflows/build-sveltecf.yaml

  verify-uniproc:
    needs: build-uniproc
    uses: ./.github/workflows/verify-uniproc.yaml

  verify-sveltecf:
    needs: build-sveltecf
    uses: ./.github/workflows/verify-sveltecf.yaml
