name: verify-sveltecf

on:
  workflow_call:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  test-and-so-on:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      STORE_PATH: ''
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache/restore@v3
        with:
          path: ${{ env.STORE_PATH}}
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install at sveltecf
        run: pnpm install
        working-directory: ./sveltecf
      - name: Restore sveletecf cache
        uses: actions/cache/restore@v3
        with:
          path: ./sveltecf/.svelte-kit
          key: sveltecf-kit-${{ github.sha }}
      - run: pnpm sveltecf test
      - run: pnpm sveltecf run lint
      - run: pnpm sveltecf run check
      - name: Install playwright
        run: pnpm sveltecf exec playwright install --with-deps
      - run: pnpm sveltecf run test
