name: verify-uniproc

on:
  workflow_call:

jobs:
  test-and-so-on:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - uses: ./.github/actions/restore-pnpm-store-cache
      - name: Install at uniproc
        run: pnpm install
        working-directory: ./uniproc
      - run: pnpm uniproc lint
      - run: pnpm uniproc test
      - run: pnpm uniproc main
